import AppKit
import os

/// Watches the general pasteboard and reports new text.
///
/// ## Why this polls
///
/// macOS publishes no notification for a pasteboard change. `NSPasteboard.changeCount` is
/// the only signal, and reading it is the cheapest call in AppKit — an integer out of a
/// shared server, no data copied. So the loop reads *only* the counter, and touches the
/// contents on the rare turn where it has actually moved. At the interval below that is a
/// handful of microseconds a second.
///
/// ## What it refuses to remember
///
/// The privacy rules live here, at the point of capture, rather than in the manager. A
/// clipboard history that records a password once has already failed, and no amount of
/// filtering afterwards undoes it:
///
/// * **`org.nspasteboard.ConcealedType`** — the marker 1Password, Bitwarden, KeePassXC and
///   others set on a copied secret. This is the real defence and the reason the convention
///   exists.
/// * **`org.nspasteboard.TransientType` / `AutoGeneratedType`** — set by apps that put
///   something on the pasteboard for a moment without the user asking, which is not
///   history.
/// * **A shape that looks generated** — see `ClipboardEntry.looksLikeSecret`. Catches the
///   manager that forgets the marker.
@MainActor
final class PasteboardMonitorService {
    /// Called with text worth remembering, and the app it came from.
    private let onCapture: (String, NSRunningApplication?) -> Void

    private var timer: Timer?
    private var lastChangeCount: Int
    private let log = Logger(subsystem: AppInfo.bundleIdentifier, category: "ClipboardHistory")

    /// Half a second. Fast enough that the item is there by the time anyone opens the
    /// history, slow enough to be free.
    private static let interval: TimeInterval = 0.5

    /// Concealed and transient markers, as declared at nspasteboard.org. Compared as raw
    /// strings because they are conventions between apps, not system-declared types.
    private static let privateTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        // 1Password's own marker, which predates the convention and is still set.
        "com.agilebits.onepassword",
    ]

    /// Longest text kept. Past this it is a document, not a clipboard item, and storing it
    /// would bloat the history file for something nobody scrolls back to.
    private static let maximumLength = 64 * 1024

    init(onCapture: @escaping (String, NSRunningApplication?) -> Void) {
        self.onCapture = onCapture
        // Start from where the pasteboard already is, so launching WhizMe does not capture
        // whatever happened to be copied before it was running.
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        guard timer == nil else { return }

        let timer = Timer.scheduledTimer(withTimeInterval: Self.interval, repeats: true) { [weak self] _ in
            // Scheduled from the main actor, so it fires on the main run loop.
            MainActor.assumeIsolated { self?.poll() }
        }
        // The default mode alone stops the loop while a menu is open or a window is being
        // dragged — exactly when someone is most likely to be copying.
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Re-syncs to the current pasteboard without capturing it.
    ///
    /// Called when the app itself writes to the pasteboard. Without it, pasting from the
    /// history re-captures what was just written and the same entry climbs to the top on
    /// every use.
    func ignoreCurrentContents() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        // The whole cost of monitoring, on every turn where nothing was copied.
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        guard let types = pasteboard.types else { return }

        // Checked before reading the string, so a concealed secret is never even loaded
        // into this process's memory.
        if types.contains(where: { Self.privateTypes.contains($0.rawValue) }) {
            log.info("Skipped a pasteboard change marked concealed or transient")
            return
        }

        guard let text = pasteboard.string(forType: .string) else { return }

        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, text.count <= Self.maximumLength else { return }

        if ClipboardEntry.looksLikeSecret(text) {
            log.info("Skipped a pasteboard change that looks like a generated secret")
            return
        }

        onCapture(text, NSWorkspace.shared.frontmostApplication)
    }
}
